name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-10-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn install
      - name: Lint Contracts
        run: npx solhint contracts/*
      - name: Lint js
        run: npx eslint scripts test
      - name: Compile contracts
        run: npx hardhat compile
      - name: Run tests
        run: npx hardhat test
