name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install
        run: yarn install
      - name: Lint Contracts
        run: npx solhint contracts/*
      - name: Lint js
        run: npx eslint scripts test
      - name: Compile contracts
        run: npx hardhat compile
      - name: Run tests
        run: npx hardhat test
